In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = '/content/sample_data/Mumbai_booking_data_CSV.csv'
df = pd.read_csv(file_path)

In [4]:
print("Shape of dataset (rows, columns):", df.shape)
print("Column names:\n", df.columns.tolist())

Shape of dataset (rows, columns): (100000, 20)
Column names:
 ['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT', 'Cancelled Rides by Customer', 'Reason for Cancelling by Customer', 'Cancelled Rides by Driver', 'Reason for Cancelling by Driver', 'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value', 'Ride Distance', 'Driver Ratings', 'Customer Rating']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               100000 non-null  object
 1   Time                               100000 non-null  object
 2   Booking ID                         100000 non-null  object
 3   Booking Status                     100000 non-null  object
 4   Customer ID                        100000 non-null  object
 5   Vehicle Type                       100000 non-null  object
 6   Pickup Location                    100000 non-null  object
 7   Drop Location                      100000 non-null  object
 8   Avg VTAT                           66833 non-null   float64
 9   Avg CTAT                           66833 non-null   float64
 10  Cancelled Rides by Customer        100000 non-null  bool
 11  Reason for Cancelling by Customer  7508 non-null    object
 12  Cancelled Rides by Driver          100000 non-null  bool
 13  Reason for Cancelling by Driver    19245 non-null   object
 14  Incomplete Rides                   100000 non-null  bool
 15  Incomplete Rides Reason            6414 non-null    object
 16  Booking Value                      66833 non-null   float64
 17  Ride Distance                      66833 non-null   float64
 18  Driver Ratings                     66833 non-null   float64
 19  Customer Rating                    66833 non-null   float64
dtypes: bool(3), float64(6), object(11)
memory usage: 13.3+ MB

In [6]:
df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                             33167
Avg CTAT                             33167
Cancelled Rides by Customer              0
Reason for Cancelling by Customer    92492
Cancelled Rides by Driver                0
Reason for Cancelling by Driver      80755
Incomplete Rides                         0
Incomplete Rides Reason              93586
Booking Value                        33167
Ride Distance                        33167
Driver Ratings                       33167
Customer Rating                      33167
dtype: int64

In [7]:
df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                             33167
Avg CTAT                             33167
Cancelled Rides by Customer              0
Reason for Cancelling by Customer    92492
Cancelled Rides by Driver                0
Reason for Cancelling by Driver      80755
Incomplete Rides                         0
Incomplete Rides Reason              93586
Booking Value                        33167
Ride Distance                        33167
Driver Ratings                       33167
Customer Rating                      33167
dtype: int64

In [8]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating
0,2025-01-21,14:55,CNR2373430247,Success,CUST907817,eBike,Area 3,Area 26,12.76,17.36,False,NaN,False,NaN,False,NaN,334.0,35.68,1.8,1.4
1,2025-01-13,14:46,CNR8825424090,Success,CUST359317,Bike,Area 3,Area 35,4.95,8.60,False,NaN,False,NaN,False,NaN,452.0,46.90,2.2,3.5
2,2025-01-20,02:54,CNR7869379373,Cancelled by Driver,CUST221126,Bike,Area 35,Area 48,NaN,NaN,False,NaN,True,Personal & Car related issues,False,NaN,NaN,NaN,NaN,NaN
3,2025-01-17,12:50,CNR2899177378,Success,CUST338656,Prime Sedan,Area 21,Area 5,12.24,12.38,False,NaN,False,NaN,False,NaN,420.0,42.66,4.5,1.9
4,2025-01-08,02:13,CNR4467207253,Success,CUST495153,eBike,Area 21,Area 18,9.69,6.06,False,NaN,False,NaN,False,NaN,370.0,41.75,1.5,4.1

In [9]:
df.describe()

,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,66833.000000,66833.000000,66833.000000,66833.000000,66833.000000,66833.000000
mean,8.010105,15.496752,431.944354,45.702126,3.002939,2.996985
std,4.035576,8.389567,296.688043,29.711784,1.151638,1.154560
min,1.000000,1.000000,50.000000,5.000000,1.000000,1.000000
25%,4.500000,8.210000,210.000000,23.520000,2.000000,2.000000
50%,8.030000,15.480000,371.000000,39.550000,3.000000,3.000000
75%,11.500000,22.760000,587.000000,61.280000,4.000000,4.000000
max,15.000000,30.000000,2000.000000,203.940000,5.000000,5.000000

In [10]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(dropna=False))

Column: Date
Date
2025-01-03    3329
2025-01-12    3323
2025-01-30    3321
2025-01-25    3304
2025-01-14    3302
2025-01-26    3291
2025-01-06    3283
2025-01-11    3269
2025-01-05    3256
2025-01-15    3250
2025-01-07    3247
2025-01-19    3243
2025-01-09    3236
2025-01-18    3233
2025-01-22    3232
2025-01-21    3231
2025-01-17    3223
2025-01-02    3222
2025-01-04    3220
2025-01-10    3216
2025-01-16    3212
2025-01-08    3205
2025-01-28    3192
2025-01-31    3188
2025-01-23    3186
2025-01-24    3179
2025-01-20    3149
2025-01-13    3135
2025-01-29    3126
2025-01-27    3100
2025-01-01    3097
Name: count, dtype: int64

Column: Time
Time
04:58    101
11:18     97
13:41     95
18:45     95
05:47     94
        ...
11:35     49
17:03     48
06:32     48
11:32     45
02:11     44
Name: count, Length: 1440, dtype: int64

Column: Booking ID
Booking ID
CNR6872972227    1
CNR5110032406    1
CNR7310635705    1
CNR6928502789    1
CNR2419122462    1
                ..
CNR4467207253    1
CNR2899177378    1
CNR7869379373    1
CNR8825424090    1
CNR2373430247    1
Name: count, Length: 100000, dtype: int64

Column: Booking Status
Booking Status
Success                  66833
Cancelled by Driver      19245
Cancelled by Customer     7508
Incomplete                6414
Name: count, dtype: int64

Column: Customer ID
Customer ID
CUST900824    4
CUST804645    4
CUST706982    4
CUST999338    4
CUST587526    4
             ..
CUST932240    1
CUST336886    1
CUST148012    1
CUST748526    1
CUST386010    1
Name: count, Length: 94696, dtype: int64

Column: Vehicle Type
Vehicle Type
Auto           14456
Mini           14439
eBike          14311
Bike           14263
Prime SUV      14236
Prime Sedan    14164
Prime Plus     14131
Name: count, dtype: int64

Column: Pickup Location
Pickup Location
Area 32    2112
Area 3     2080
Area 33    2068
Area 22    2066
Area 13    2052
Area 38    2049
Area 27    2049
Area 17    2045
Area 31    2043
Area 14    2043
Area 34    2041
Area 41    2037
Area 11    2035
Area 19    2034
Area 24    2030
Area 23    2025
Area 29    2020
Area 37    2019
Area 43    2016
Area 10    2015
Area 48    2015
Area 46    2014
Area 39    2004
Area 28    2004
Area 16    2003
Area 36    2003
Area 50    2001
Area 45    2000
Area 35    1997
Area 21    1992
Area 15    1986
Area 1     1986
Area 49    1978
Area 20    1978
Area 2     1978
Area 30    1974
Area 42    1973
Area 47    1969
Area 5     1965
Area 4     1959
Area 7     1949
Area 6     1947
Area 25    1944
Area 26    1943
Area 8     1943
Area 12    1942
Area 40    1930
Area 18    1925
Area 9     1925
Area 44    1894
Name: count, dtype: int64

Column: Drop Location
Drop Location
Area 18    2092
Area 36    2069
Area 6     2058
Area 8     2049
Area 29    2037
Area 27    2036
Area 35    2033
Area 1     2033
Area 34    2033
Area 9     2033
Area 16    2032
Area 40    2031
Area 22    2029
Area 46    2026
Area 3     2021
Area 44    2021
Area 23    2020
Area 14    2020
Area 4     2020
Area 26    2018
Area 12    2018
Area 43    2016
Area 21    2008
Area 49    2006
Area 11    2005
Area 32    2005
Area 39    2002
Area 2     2001
Area 24    1997
Area 7     1996
Area 13    1992
Area 41    1992
Area 45    1991
Area 38    1987
Area 37    1983
Area 20    1982
Area 47    1974
Area 30    1971
Area 25    1969
Area 42    1965
Area 15    1963
Area 28    1959
Area 33    1956
Area 19    1951
Area 5     1945
Area 48    1942
Area 17    1937
Area 31    1933
Area 50    1932
Area 10    1911
Name: count, dtype: int64

Column: Reason for Cancelling by Customer
Reason for Cancelling by Customer
NaN                                             92492
Wrong Address                                    1535
AC is not working                                1533
Driver is not moving towards pickup location     1496
Driver asked to cancel                           1479
Change of plans                                  1465
Name: count, dtype: int64

Column: Reason for Cancelling by Driver
Reason for Cancelling by Driver
NaN                                    80755
Customer related issue                  4868
The customer was coughing/sick          4800
More than permitted people in there     4790
Personal & Car related issues           4787
Name: count, dtype: int64

Column: Incomplete Rides Reason
Incomplete Rides Reason
NaN                  93586
Vehicle Breakdown     2163
Customer Demand       2130
Other Issue           2121
Name: count, dtype: int64